%% Import data from text file.
% Script for importing data from the following text file:
%
%    /fs/data/bengis/Papers/SandyWithoutSLR/Bitterman counterfactuals/historical_CMIP35_index.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/06/30 17:43:36

%% Initialize variables.
filename = '/fs/data/bengis/Papers/SandyWithoutSLR/Bitterman counterfactuals/historical_CMIP35_index.dat';
startRow = 76;

%% Format for each line of text:
%   column1: double (%f)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%3f%17s%9s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Remove white space around all cell columns.
dataArray{2} = strtrim(dataArray{2});
dataArray{3} = strtrim(dataArray{3});
dataArray{4} = strtrim(dataArray{4});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
historicalCMIP35index = table;
historicalCMIP35index.Ind = dataArray{:, 1};
historicalCMIP35index.exofmodelswhos = cellstr(dataArray{:, 2});
historicalCMIP35index.edatais = cellstr(dataArray{:, 3});
historicalCMIP35index.usedinhistorical_CMIP35_tasdat = cellstr(dataArray{:, 4});

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;